--- UPDATE NGAY VIP
GO
CREATE PROCEDURE UPDATEVIP
(@USERID NVARCHAR(50),@MANAP SMALLINT)
AS
BEGIN
	IF(@MANAP=1)
		BEGIN 
			UPDATE [User]
			SET So_Ngay_Vip=So_Ngay_Vip+7
			WHERE USER_ID=@USERID
		END
	ELSE IF(@MANAP=2)
		BEGIN 
			UPDATE [User]
			SET So_Ngay_Vip=So_Ngay_Vip+30
			WHERE USER_ID=@USERID
		END
	ELSE IF(@MANAP=3)
		BEGIN 
			UPDATE [User]
			SET So_Ngay_Vip=So_Ngay_Vip+90
			WHERE USER_ID=@USERID
		END
	ELSE IF(@MANAP=4)
		BEGIN 
			UPDATE [User]
			SET So_Ngay_VIP=So_Ngay_Vip+365
			WHERE USER_ID=@USERID
		END
END
EXEC  UPDATEVIP 'cbao','1'

